# Numpy

# Why Numpy

1.Arithmatic Oprations 2.Bitwise Oprations 3.Stacking 4.Mathematical Oprations 5.Statistical Oprations

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
x=np.array([1,2,3,4,5,6,7])
type(x)

numpy.ndarray

In [5]:
len(x)

7

In [6]:
print(x.shape)
print(x.ndim)

(7,)
1


In [9]:
x=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(x)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [10]:
print(x.shape)
print(x.ndim)
print(type(x))

(2, 5)
2
<class 'numpy.ndarray'>


In [11]:
x=np.array([[1,2,3,4,5],[5,6,7,8,]])
print(x)
print(type(x))
print(x.shape)
print(x.ndim)

[list([1, 2, 3, 4, 5]) list([5, 6, 7, 8])]
<class 'numpy.ndarray'>
(2,)
1


C:\Users\pandy\AppData\Local\Temp\ipykernel_6244\861718746.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x=np.array([[1,2,3,4,5],[5,6,7,8,]])


In [12]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(type(x))
print(x.shape)
print(x.ndim)

<class 'numpy.ndarray'>
(3, 3)
2


In [16]:
x=np.array([[[1,2,3],[3,4,5],[4,5,6]],[[2,3,4],[4,5,6],[6,7,8]],[[4,5,6],[5,6,7],[8,9,7]]])
print(x)
print(x.shape)

[[[1 2 3]
  [3 4 5]
  [4 5 6]]

 [[2 3 4]
  [4 5 6]
  [6 7 8]]

 [[4 5 6]
  [5 6 7]
  [8 9 7]]]
(3, 3, 3)


In [17]:
A=np.array([1,5,8,9])
B=np.array([4,5,4,4])
print(A+B)
print(A*B)

[ 5 10 12 13]
[ 4 25 32 36]


In [18]:
A=np.array([1,5,8,9])
B=np.array([4,5,4,4])
print(A)
print(B)
print(A.dot(B))

[1 5 8 9]
[4 5 4 4]
97


# Random Number Generator Using Numpy# 

In [20]:
from numpy import random
random.seed(11)
x=random.randint(1,110)
print(x)

26


In [21]:
#Generate random float number
#random.seed(2)
x=random.rand()
print(x)

0.06830684110131291


In [22]:
random.randint(20,100, size=(30))

array([75, 33, 96, 53, 91, 44, 68, 52, 65, 24, 54, 32, 21, 94, 57, 44, 37,
       87, 90, 63, 84, 99, 43, 47, 90, 30, 77, 47, 64, 34])

In [23]:
#generate a 2-d array with 3 row, each contain 5 elements
from numpy import random
x=random.randint(1,100,size=(3,3,3))
print(x)

[[[ 8 56 80]
  [65 41 28]
  [96  6 54]]

 [[72 51 60]
  [ 2  4  9]
  [88 82 69]]

 [[73 33 79]
  [20 26 91]
  [39 60 18]]]


# Creating Scalars in Numpy# 

In [24]:
#numpy.asscalar()
import numpy as np
in_arr=np.array([7])
print("input array is",in_arr)
out_scalar=np.asscalar(in_arr)
print("output scalar form input array",out_scalar)

input array is [7]
output scalar form input array 7


C:\Users\pandy\AppData\Local\Temp\ipykernel_6244\1630172804.py:5: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar=np.asscalar(in_arr)


In [25]:
import numpy as np
in_arr=np.array([7,2])
print("input array is",in_arr)
out_scalar=np.asscalar(in_arr[1])
print("output scalar form input array",out_scalar)

input array is [7 2]
output scalar form input array 2


C:\Users\pandy\AppData\Local\Temp\ipykernel_6244\575476275.py:4: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar=np.asscalar(in_arr[1])


# Creating a Vactor in Numpy

In [27]:
list1=[1,2,3]
#creating list vertical
list2=[[10],
       [20],
       [30]]
print(list1)
print(list2)
print(list1+list2)
print(type(list1))
list2[0][0]

[1, 2, 3]
[[10], [20], [30]]
[1, 2, 3, [10], [20], [30]]
<class 'list'>


10

# Creating Matrix in Numpy

In [28]:
import numpy as np
a=np.matrix('1,2;3,4')
print("via string input:\n",a,"\n\n")
#array like input
b=np.matrix([[5,6],[3,4]])
print("via array like input:\n",b)

via string input:
 [[1 2]
 [3 4]] 


via array like input:
 [[5 6]
 [3 4]]


In [29]:
import numpy as np
a=np.matrix('1,2;3,4')
print("via string input:\n",a,"\n\n")
#array like input
b=np.matrix([[5,6],[3,4]])
print("via array like input:\n",b)
print(a*b)

via string input:
 [[1 2]
 [3 4]] 


via array like input:
 [[5 6]
 [3 4]]
[[11 14]
 [27 34]]
